// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCipsiLSqQeXAQkTJJPtWTuHjf37fVG8Wc',
    appId: '1:1082816030637:web:580813f02830d56f4b2324',
    messagingSenderId: '1082816030637',
    projectId: 'cubing-b1061',
    authDomain: 'cubing-b1061.firebaseapp.com',
    storageBucket: 'cubing-b1061.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNk00b0I0fqG9c1gb3qVuphcr_G9le-us',
    appId: '1:1082816030637:android:847e747e9035d4ae4b2324',
    messagingSenderId: '1082816030637',
    projectId: 'cubing-b1061',
    storageBucket: 'cubing-b1061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0AxDXBnFuTX9RJn1bl6k6XfIh23pPiQk',
    appId: '1:1082816030637:ios:8049efc1d7b40afa4b2324',
    messagingSenderId: '1082816030637',
    projectId: 'cubing-b1061',
    storageBucket: 'cubing-b1061.firebasestorage.app',
    iosBundleId: 'com.example.cubeOff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0AxDXBnFuTX9RJn1bl6k6XfIh23pPiQk',
    appId: '1:1082816030637:ios:8049efc1d7b40afa4b2324',
    messagingSenderId: '1082816030637',
    projectId: 'cubing-b1061',
    storageBucket: 'cubing-b1061.firebasestorage.app',
    iosBundleId: 'com.example.cubeOff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCipsiLSqQeXAQkTJJPtWTuHjf37fVG8Wc',
    appId: '1:1082816030637:web:fc53fb7df08ed7ce4b2324',
    messagingSenderId: '1082816030637',
    projectId: 'cubing-b1061',
    authDomain: 'cubing-b1061.firebaseapp.com',
    storageBucket: 'cubing-b1061.firebasestorage.app',
  );
}
